server:
  port: 0
spring:
  application:
    name: controller
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/development
        opaquetoken:
          client-id: SpringKeycloakSecurity
          client-secret: CBcGD21ehXdvNaot2ZKEhNGoCKsRFyBw
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: password
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:password@localhost:8761/eureka
